### ISSUE TITLE
metadata of existing volumes

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/pyCEURmake#11]
use grobid to extract the metadata of the existing documents

**Comment by tholzheim** [comment]
If a corresponding volume is indexed in dblp than the metadata shall be available for this system.
By extracting it from the ConferenceCorpus see https://github.com/WolfgangFahl/ConferenceCorpus/issues/6

**Comment by WolfgangFahl** [comment]
This should work without the need for implementing https://github.com/WolfgangFahl/pyFlaskBootstrap4/issues/14 since there are only some 3000 Volumes to consider

**Comment by WolfgangFahl** [comment]
This now works and further details need detailed issues
