### ISSUE TITLE
Named queries 

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/pyCEURmake#12]
see https://github.com/ailabitmo/sempubchallenge2014-task1

Query Manager of pyLODStorage could be useful https://github.com/WolfgangFahl/pyLoDStorage/blob/master/lodstorage/query.py

**Comment by WolfgangFahl** [comment]
limit to sensible queries

**Comment by WolfgangFahl** [comment]
Example:
```
Identify all countries that the authors of all regular papers in workshop W were from
```

**Comment by WolfgangFahl** [comment]
https://github.com/ceurws/lod/wiki/SemPub15_Task1
