### ISSUE TITLE
dblp event synchronization - low hanging fruit (first decile)

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pyCEURmake#27]
Start with easy to identify dblp events - create wikidata item for evet and link event with CEUR-WS Proceedings
via is proceedings from. Set dblp eventID. Fix SPARQL query and example.

**Comment by tholzheim** [comment]
https://www.wikidata.org/wiki/Property_talk:P10692

**Comment by tholzheim** [comment]
Steps:
1) get wikidataId and urn of volumes from wikidata
2) based on urn query dblp for the corresponding DBLPeventID
3) build record
   * build DBLPeventID from returned dblp entity id
   *  try to extract event title
   * generate event description
4) Create event in wikidata
5) add relation between proceeding and event
