### ISSUE TITLE
Extraction of start time & end time

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/pyCEURmake#33]
For Volume 0-558 the date information for the event is contained in the title
For Volume 559-3200+ the date information for the event is contained in the loctime property

**Comment by tholzheim** [comment]
Extraction completed up to volume 3207.

```sparql
SELECT DISTINCT (COUNT(?startTime) as ?numberOfStartDates) (COUNT(?endTime) as ?numberOfEndDates){
    ?proceedings p:P179 [ps:P179 wd:Q27230297;
                         pq:P478 ?volume];
                 wdt:P4745 ?event.
  OPTIONAL{?event wdt:P580 ?startTime}
  OPTIONAL{?event wdt:P582 ?endTime}
         

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
  }
} 
```
[Try it!](https://query.wikidata.org/#SELECT%20DISTINCT%20%28COUNT%28%3FstartTime%29%20as%20%3FnumberOfStartDates%29%20%28COUNT%28%3FendTime%29%20as%20%3FnumberOfEndDates%29%7B%0A%20%20%20%20%3Fproceedings%20p%3AP179%20%5Bps%3AP179%20wd%3AQ27230297%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP478%20%3Fvolume%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wdt%3AP4745%20%3Fevent.%0A%20%20OPTIONAL%7B%3Fevent%20wdt%3AP580%20%3FstartTime%7D%0A%20%20OPTIONAL%7B%3Fevent%20wdt%3AP582%20%3FendTime%7D%0A%20%20%20%20%20%20%20%20%20%0A%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%0A%20%20%7D%0A%7D%20)
Results:
* numberOfStartDates: 3317
* numberOfEndDates: 3317
> some volumes consist of multiple workshops thus the number of dates is higher than the number of workshops

**Comment by tholzheim** [comment]
Integration into into the default event creation process is still required

**Comment by tholzheim** [comment]
>FYI: Dates were often separated by a dash (one of):
>* `-` _HYPHEN-MINUS_
>* `‐` _HYPHEN_
>* `–` _EN DASH_

**Comment by WolfgangFahl** [comment]
@tholzheim - great job
You might want to fix the [invalid dates](https://query.wikidata.org/#SELECT%20%3FstartTime%20%3FendTime%20%3Fvolume%20%7B%0A%20%20%20%20%3Fproceedings%20p%3AP179%20%5Bps%3AP179%20wd%3AQ27230297%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP478%20%3Fvolume%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wdt%3AP4745%20%3Fevent.%0A%20%20OPTIONAL%7B%3Fevent%20wdt%3AP580%20%3FstartTime%7D%0A%20%20OPTIONAL%7B%3Fevent%20wdt%3AP582%20%3FendTime%7D%0A%20%20%20%20%20%20%20%20%20%0A%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%0A%20%20%7D%0A%7D%20ORDER%20BY%20DESC%28%3FendTime%29)

**Comment by tholzheim** [comment]
The issue occurred on volumes that took place at two dates instead of date range
e.g. `October 23th and 26th, 2011`
To normalize the dates the dates were assigned to `start time` and `end time` instead of defining two `point in time` values.
> The issue only was present on 4 volumes

> The dates in October 2022 are correctly extracted even though they are in the future
