### ISSUE TITLE
Extraction of Papers 

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/pyCEURmake#36]
Extraction of Papers  this includes:
* paper [title](https://www.wikidata.org/wiki/Property:P1476)
* authors (as [author name string](https://www.wikidata.org/wiki/Q73980831) or optimal as [author item](https://www.wikidata.org/wiki/Property:P50) with dblp author ID)
* paper url ([full work available at URL (P953)](https://www.wikidata.org/wiki/Property:P953))
* [publication date](https://www.wikidata.org/wiki/Property:P577)
* [published in](https://www.wikidata.org/wiki/Property:P1433) (link to proceedings)

**Comment by WolfgangFahl** [comment]
Descriptions such as
```
Text2KG 2022 Workhop paper published in CEUR-WS Volume 3184
```
would be good see https://www.wikidata.org/wiki/Q117040466

**Comment by WolfgangFahl** [comment]
make sure we cover the extraction capabilities of https://github.com/WDscholia/scholia/blob/master/scholia/scrape/ceurws.py
