### ISSUE TITLE
wikidata sync count of proceedings

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pyCEURmake#38]
I think the reported number of proceedings is incorrect:

found 3346 wikidata CEUR-WS proceedings records
![grafik](https://user-images.githubusercontent.com/1336221/190956714-3ab52703-e402-4c14-98c5-720ee00e1c58.png)

**Comment by tholzheim** [comment]
The Proceedings query does not account for joint proceedings that `is proceedings from` multiple events. Thus, the query yields for each proceeding with `n` events `n` records.
