### ISSUE TITLE
CEUR-WS returns more results than expected

### ISSUE THREAD

**Issue by VladimirAlexiev** [WolfgangFahl/pyCEURmake#49]
http://ceur-ws-browser.bitplan.com/wikidatasync, click `Refresh Wikidata`.
It runs a SPARQL query then says "It found 3331 wikidata CEUR-WS proceedings records".
But the largest number is `Vol-3323`: even if CEUR have no gaps in their sequence, that's less than the WD results.

So I think the query is a bit wrong: some field is multi-valued (even though it's reasonable to assume it would be single-valued), so you get duplicate rows for the same volume.

**Comment by WolfgangFahl** [comment]
@VladimirAlexiev: #45 states a need to improve the query anyways and it looks we are running into the problems that we wrote about in https://ceur-ws.org/Vol-3262/paper7.pdf

**Comment by VladimirAlexiev** [comment]
@WolfgangFahl I answered in #45: need to use `UNION` instead of `OPTIONAL` for multi-valued fields.

However, the difference of rows in this particular issue is pretty small: could you find the "duplicate" rows and then we analyze the reason?

**Comment by WolfgangFahl** [comment]
https://cr.bitplan.com/index.php/List_of_Queries has a list of queries now 
e.g. https://cr.bitplan.com/index.php/Q0.1 might work better
