### ISSUE TITLE
paper NEL with dblp

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pyCEURmake#70]
papers_dblp.json should deliver the paper information from dblp's SPARQL endpoint which are linkable to CEUR-WS papers.

Identifier should be Vol_#+pdf_name (aka full work available stripped by http://ceur-ws and .pdf ) 
e.g. Vol-3262/paper1

**Comment by WolfgangFahl** [comment]
Example ttl
```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix bf: <http://id.loc.gov/ontologies/bibframe/> .
@prefix bibo: <http://purl.org/ontology/bibo/> .
@prefix bibtex: <http://purl.org/net/nknouf/ns/bibtex#> .
@prefix cito: <http://purl.org/spar/cito/> .
@prefix datacite: <http://purl.org/spar/datacite/> .
@prefix dbo: <http://dbpedia.org/ontology/> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix litre: <http://purl.org/spar/literal/> .
@prefix locid: <http://id.loc.gov/vocabulary/identifiers/> .
@prefix locrel: <http://id.loc.gov/vocabulary/relators/> .
@prefix schema: <https://schema.org/> .
@prefix wd: <http://www.wikidata.org/entity/> .
@prefix wdt: <http://www.wikidata.org/prop/direct/> .
@prefix dblp: <https://dblp.org/rdf/schema#> .

<https://dblp.org/rec/conf/esws/BrylBEK14>
	rdfs:label "Volha Bryl et al.: What's in the proceedings? Combining publisher's and researcher's perspectives. (2014)" ;
	datacite:hasIdentifier [
		datacite:usesIdentifierScheme datacite:dblp-record ;
		litre:hasLiteralValue "conf/esws/BrylBEK14" ;
		a datacite:ResourceIdentifier
	] ;
	dblp:title "What's in the proceedings? Combining publisher's and researcher's perspectives." ;
	dblp:bibtexType bibtex:Inproceedings ;
	dblp:authoredBy <https://dblp.org/pid/91/5826>, <https://dblp.org/pid/85/3763>, <https://dblp.org/pid/22/5420-1>, <https://dblp.org/pid/146/7984> ;
	dblp:numberOfCreators 4 ;
	dblp:hasSignature [
		dblp:signatureDblpName "Volha Bryl" ;
		dblp:signatureCreator <https://dblp.org/pid/91/5826> ;
		dblp:signatureOrdinal 1 ;
		dblp:signaturePublication <https://dblp.org/rec/conf/esws/BrylBEK14> ;
		a dblp:AuthorSignature
	], [
		dblp:signatureDblpName "Aliaksandr Birukou" ;
		dblp:signatureCreator <https://dblp.org/pid/85/3763> ;
		dblp:signatureOrdinal 2 ;
		dblp:signaturePublication <https://dblp.org/rec/conf/esws/BrylBEK14> ;
		a dblp:AuthorSignature
	], [
		dblp:signatureDblpName "Kai Eckert 0001" ;
		dblp:signatureCreator <https://dblp.org/pid/22/5420-1> ;
		dblp:signatureOrdinal 3 ;
		dblp:signaturePublication <https://dblp.org/rec/conf/esws/BrylBEK14> ;
		a dblp:AuthorSignature
	], [
		dblp:signatureDblpName "Mirjam Kessler" ;
		dblp:signatureCreator <https://dblp.org/pid/146/7984> ;
		dblp:signatureOrdinal 4 ;
		dblp:signaturePublication <https://dblp.org/rec/conf/esws/BrylBEK14> ;
		a dblp:AuthorSignature
	] ;
	dblp:primaryDocumentPage <https://ceur-ws.org/Vol-1155/paper-01.pdf> ;
	dblp:documentPage <https://ceur-ws.org/Vol-1155/paper-01.pdf> ;
	dblp:listedOnTocPage <https://dblp.org/db/conf/esws/sepublica2014> ;
	dblp:publishedIn "SePublica" ;
	dblp:publishedInBook "SePublica" ;
	dblp:yearOfEvent "2014" ;
	dblp:yearOfPublication "2014" ;
	dblp:publishedAsPartOf <https://dblp.org/rec/conf/esws/2014sepublica> ;
	a dblp:Publication, dblp:Inproceedings .
<https://dblp.org/rec/conf/esws/BrylBEK14.ttl>
	rdfs:label "provenance information for RDF data of dblp record 'conf/esws/BrylBEK14'" ;
	dct:creator <https://dblp.org> ;
	dct:isPartOf <https://dblp.org/rdf/dblp.ttl> ;
	dct:modified "2023-03-10T16:23:13+0100" ;
	dct:license <https://creativecommons.org/publicdomain/zero/1.0/> .
```

**Comment by WolfgangFahl** [comment]
Important fields:
- url https://dblp.org/rec/conf/esws/BrylBEK14
- title: What's in the proceedings? Combining publisher's and researcher's perspectives.
- publishedAsPartOf https://dblp.org/rec/conf/esws/2014sepublica
- authoredBy https://dblp.org/pid/91/5826, https://dblp.org/pid/85/3763, https://dblp.org/pid/22/5420-1, https://dblp.org/pid/146/7984

**Comment by tholzheim** [comment]
Query to get all authors by paper dblp id:
```sparql
PREFIX datacite: <http://purl.org/spar/datacite/>
PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX litre: <http://purl.org/spar/literal/>
SELECT ?author ?wd_qid
WHERE{
    BIND(<https://dblp.org/rec/conf/esws/BrylBEK14> as ?paper)
    ?paper dblp:title ?title .
    ?paper dblp:authoredBy ?author.
    OPTIONAL{
        ?author datacite:hasIdentifier ?wd_blank.
        ?wd_blank datacite:usesIdentifierScheme datacite:wikidata.
        ?wd_blank litre:hasLiteralValue ?wd_qid.
    }
}
```
[Try it!](https://qlever.cs.uni-freiburg.de/dblp-plus/vIeAMq?exec=true)

**Comment by WolfgangFahl** [comment]
sparqlquery -en dbis-dblp -qp dblp.yaml -qn "CEUR-WS Counts" -f github
## CEUR-WS Counts

### query
```sparql
PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (COUNT(DISTINCT ?author) as ?numberOfAuthors) 
       (COUNT(DISTINCT ?paper) as ?numberOfPapers) 
       (COUNT(DISTINCT ?editor) as ?numberOfEditors)
       (COUNT(DISTINCT ?proceeding) as ?numberOfVolumes)
WHERE { 
    ?proceeding dblp:publishedIn "CEUR Workshop Proceedings".
    OPTIONAL{?proceeding dblp:editedBy ?editor}
    OPTIONAL{
        ?paper dblp:publishedAsPartOf ?proceeding.
        OPTIONAL{?paper dblp:authoredBy ?author}
    }

}

```
[try it!](http://dblp.wikidata.dbis.rwth-aachen.de/api/dblp?query=PREFIX%20dblp%3A%20%3Chttps%3A//dblp.org/rdf/schema%23%3E%0APREFIX%20xsd%3A%20%3Chttp%3A//www.w3.org/2001/XMLSchema%23%3E%0ASELECT%20%28COUNT%28DISTINCT%20%3Fauthor%29%20as%20%3FnumberOfAuthors%29%20%0A%20%20%20%20%20%20%20%28COUNT%28DISTINCT%20%3Fpaper%29%20as%20%3FnumberOfPapers%29%20%0A%20%20%20%20%20%20%20%28COUNT%28DISTINCT%20%3Feditor%29%20as%20%3FnumberOfEditors%29%0A%20%20%20%20%20%20%20%28COUNT%28DISTINCT%20%3Fproceeding%29%20as%20%3FnumberOfVolumes%29%0AWHERE%20%7B%20%0A%20%20%20%20%3Fproceeding%20dblp%3ApublishedIn%20%22CEUR%20Workshop%20Proceedings%22.%0A%20%20%20%20OPTIONAL%7B%3Fproceeding%20dblp%3AeditedBy%20%3Feditor%7D%0A%20%20%20%20OPTIONAL%7B%0A%20%20%20%20%20%20%20%20%3Fpaper%20dblp%3ApublishedAsPartOf%20%3Fproceeding.%0A%20%20%20%20%20%20%20%20OPTIONAL%7B%3Fpaper%20dblp%3AauthoredBy%20%3Fauthor%7D%0A%20%20%20%20%7D%0A%0A%7D%0A)
## result
|   numberOfAuthors |   numberOfPapers |   numberOfEditors |   numberOfVolumes |
|-------------------|------------------|-------------------|-------------------|
|             75762 |            47968 |              4974 |              2568 |

**Comment by WolfgangFahl** [comment]
```yaml
'dbis-dblp':
  endpoint: http://dblp.wikidata.dbis.rwth-aachen.de/api/dblp
  website: http://dblp.wikidata.dbis.rwth-aachen.de/api/dblp
  database: dbis 
  method: POST
  lang: sparql
  prefixes: |
    PREFIX dblp: <https://dblp.org/rdf/schema#>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

```

**Comment by tholzheim** [comment]
sparqlquery -en dbis-dblp -qp dblp.yaml -qn "CEUR-WS all Papers" -f github
## CEUR-WS all Papers

### query
```sparql
PREFIX datacite: <http://purl.org/spar/datacite/>
PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX litre: <http://purl.org/spar/literal/>
SELECT DISTINCT
   ?proceeding
   ?paper 
   (SAMPLE(?_title) as ?title)
   (SAMPLE(?_pdf_url) as ?pdf_url)
   (GROUP_CONCAT(?_author; SEPARATOR=";") as ?author)
  WHERE{
    ?proceeding dblp:publishedIn "CEUR Workshop Proceedings".
    ?paper dblp:publishedAsPartOf ?proceeding.
    OPTIONAL{?paper dblp:title ?_title .}
    OPTIONAL{?paper dblp:documentPage ?_pdf_url}
    OPTIONAL{?paper dblp:authoredBy ?_author}
}
GROUP BY ?proceeding ?paper

```
[try it!](http://dblp.wikidata.dbis.rwth-aachen.de/api/dblp?query=PREFIX%20datacite%3A%20%3Chttp%3A//purl.org/spar/datacite/%3E%0APREFIX%20dblp%3A%20%3Chttps%3A//dblp.org/rdf/schema%23%3E%0APREFIX%20litre%3A%20%3Chttp%3A//purl.org/spar/literal/%3E%0ASELECT%20DISTINCT%0A%20%20%20%3Fproceeding%0A%20%20%20%3Fpaper%20%0A%20%20%20%28SAMPLE%28%3F_title%29%20as%20%3Ftitle%29%0A%20%20%20%28SAMPLE%28%3F_pdf_url%29%20as%20%3Fpdf_url%29%0A%20%20%20%28GROUP_CONCAT%28%3F_author%3B%20SEPARATOR%3D%22%3B%22%29%20as%20%3Fauthor%29%0A%20%20WHERE%7B%0A%20%20%20%20%3Fproceeding%20dblp%3ApublishedIn%20%22CEUR%20Workshop%20Proceedings%22.%0A%20%20%20%20%3Fpaper%20dblp%3ApublishedAsPartOf%20%3Fproceeding.%0A%20%20%20%20OPTIONAL%7B%3Fpaper%20dblp%3Atitle%20%3F_title%20.%7D%0A%20%20%20%20OPTIONAL%7B%3Fpaper%20dblp%3AdocumentPage%20%3F_pdf_url%7D%0A%20%20%20%20OPTIONAL%7B%3Fpaper%20dblp%3AauthoredBy%20%3F_author%7D%0A%7D%0AGROUP%20BY%20%3Fproceeding%20%3Fpaper%0A%0A)
## result
| proceeding                                | paper                                      | title                                                                                                                    | pdf_url                                       | author                                                                                                                          |
|-------------------------------------------|--------------------------------------------|--------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|
| https://dblp.org/rec/conf/aaai/2019affcon | https://dblp.org/rec/conf/aaai/BaeCS19     | Modeling Happiness Using One-Class Autoencoder.                                                                          | https://ceur-ws.org/Vol-2328/4_6_paper_31.pdf | https://dblp.org/pid/27/1166>;<https://dblp.org/pid/58/2569>;<https://dblp.org/pid/73/5670                                      |
| https://dblp.org/rec/conf/aaai/2019affcon | https://dblp.org/rec/conf/aaai/ChenH19     | Adversarial and Cooperative Correlated Domain Adaptation based Multimodal Emotion Recognition.                           | https://ceur-ws.org/Vol-2328/3_paper_14.pdf   | https://dblp.org/pid/250/5988>;<https://dblp.org/pid/313/2707>;<https://dblp.org/pid/57/6633                                    |
| https://dblp.org/rec/conf/aaai/2019affcon | https://dblp.org/rec/conf/aaai/ChhayaJSU19 | Editorial for the 2nd Workshop on Affective Content Analysis (AffCon) at AAAI 2019.                                      | https://ceur-ws.org/Vol-2328/editorial.pdf    | https://dblp.org/pid/u/LyleHUngar>;<https://dblp.org/pid/83/9923>;<https://dblp.org/pid/120/2076>;<https://dblp.org/pid/62/8212 |
| https://dblp.org/rec/conf/aaai/2019affcon | https://dblp.org/rec/conf/aaai/Claeser19   | Affective Content Classification using Convolutional Neural Networks.                                                    | https://ceur-ws.org/Vol-2328/4_8_paper_33.pdf | https://dblp.org/pid/212/0085                                                                                                   |
| https://dblp.org/rec/conf/aaai/2019affcon | https://dblp.org/rec/conf/aaai/GuptaBY19   | What Constitutes Happiness? Predicting and Characterizing the Ingredients of Happiness Using Emotion Intensity Analysis. | https://ceur-ws.org/Vol-2328/4_3_paper_22.pdf | https://dblp.org/pid/131/8318>;<https://dblp.org/pid/60/6029>;<https://dblp.org/pid/66/12       
> Limited to 5
